FROM php:fpm-alpine

RUN docker-php-ext-install mysqli pdo pdo_mysql
RUN npm install

RUN a2enmod rewrite

COPY . /var/www/html/
WORKDIR /var/www/html/

RUN chown -R www-data:www-data /var/www/html

EXPOSE 8080



